name: Deploy Astro site to GitHub Pages
permissions:
  contents: write

on:
  push:
    branches:
      - main  # Adjust if your main branch is different
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run build  # Make sure 'build' is defined in your package.json scripts

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Ensure this is where Astro's output files are located

